# Generated by Django 3.2.17 on 2023-02-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleCalendar', '0002_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('job', '仕事'), ('hobby', '趣味'), ('university', '大学')], max_length=200, null=True),
        ),
    ]
